-- MySQL Script generated by MySQL Workbench
-- Mon Jan  8 10:42:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
-- Система online-аптека. Клиенты выбирают препарат из списка доступных и заказывают определенное количество. Есть препараты, требующие рецепта врача. Врач может назначить клиенту рецепт. Администратор может банить пользоваетелей.

-- -----------------------------------------------------
-- Schema pharmacy
--
-- Система online-аптека. Клиенты выбирают препарат из списка доступных и заказывают определенное количество. Есть препараты, требующие рецепта врача. Врач может назначить клиенту рецепт. Администратор может банить пользоваетелей.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `pharmacy` ;

-- -----------------------------------------------------
-- Table `pharmacy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`user` (
  `login` VARCHAR(20) NOT NULL COMMENT 'Логин пользователя',
  `name` VARCHAR(20) NOT NULL COMMENT 'Имя пользователя',
  `surname` VARCHAR(25) NOT NULL COMMENT 'Фамилия пользователя',
  `password` VARCHAR(64) NOT NULL COMMENT 'Пароль пользователя',
  `role` ENUM('doctor', 'user', 'admin', 'pharmacist') NOT NULL DEFAULT 'user' COMMENT 'Роль пользователя в рамках системы, поумолчанию \'client\', так как любой пользователь, только прошедший регистрацию является клиентом',
  `email` VARCHAR(25) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`login`),
  INDEX `login_idx` (`login` ASC)  COMMENT 'Индексация поля, хранящего логин, нужна так как это в наиболее часто используемых запросах используется данное поле ')
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая информацию о пользователях';


-- -----------------------------------------------------
-- Table `pharmacy`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`manufacturer` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'Идентификацииный номер производителя',
  `country_code` VARCHAR(3) NOT NULL,
  `phone_number` VARCHAR(70) NULL,
  `email` VARCHAR(50) NULL COMMENT 'Адрес электронной почты производителя',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая производителей препаратов';


-- -----------------------------------------------------
-- Table `pharmacy`.`drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`drug` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'Идентификационный номер препарата',
  `manufacturer_id` MEDIUMINT NULL COMMENT 'Идентификационный номер производителя данного препарата',
  `dosage` MEDIUMINT NOT NULL COMMENT 'Дозировка препарата',
  `amount` MEDIUMINT NOT NULL COMMENT 'Количество препарата в упаковке(шт)',
  `number` MEDIUMINT NOT NULL DEFAULT 0 COMMENT 'Количество упаковок перапарата на складе(шт)',
  `price` DECIMAL(6,2) NOT NULL COMMENT 'Цена препарата',
  `need_prescription` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Нужен ли рецепт для заказа',
  PRIMARY KEY (`id`),
  INDEX `manufacturer_id_idx` (`manufacturer_id` ASC),
  CONSTRAINT `fk_manufacturer_id`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `pharmacy`.`manufacturer` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая характеристики препаратов';


-- -----------------------------------------------------
-- Table `pharmacy`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`language` (
  `language_name` VARCHAR(15) NOT NULL COMMENT 'Код языка',
  PRIMARY KEY (`language_name`))
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая языки локализации';


-- -----------------------------------------------------
-- Table `pharmacy`.`drug_translate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`drug_translate` (
  `drug_id` MEDIUMINT NOT NULL COMMENT 'Идентификационный номер препарата',
  `lang_name` VARCHAR(15) NOT NULL COMMENT 'Код языка локализации',
  `name` VARCHAR(70) NOT NULL COMMENT 'Наименование препарата',
  `description` VARCHAR(200) NULL COMMENT 'Описание препарата',
  `composition` VARCHAR(100) NULL COMMENT 'Состав препарата',
  INDEX `drug_id_idx` (`drug_id` ASC),
  INDEX `lang_code_idx` (`lang_name` ASC),
  INDEX `name_idx` (`name` ASC)  COMMENT 'Постоянно используется поиск по наименованию, сортировка по наименованию ',
  CONSTRAINT `fk_drug_id`
    FOREIGN KEY (`drug_id`)
    REFERENCES `pharmacy`.`drug` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_language_code`
    FOREIGN KEY (`lang_name`)
    REFERENCES `pharmacy`.`language` (`language_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая локализованную информацию о препаратах';


-- -----------------------------------------------------
-- Table `pharmacy`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`orders` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT 'Идентификационный номер заказа',
  `client_login` VARCHAR(20) NOT NULL COMMENT 'Идентификационный номер пользователя',
  `drug_id` MEDIUMINT NOT NULL COMMENT 'Идентификационный номер препарата',
  `number` SMALLINT NOT NULL COMMENT 'Количество упаковок препарата, заказанного пользоваетелем',
  `date` DATETIME NULL,
  INDEX `drug_id_idx` (`drug_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `b_idx` (`client_login` ASC),
  CONSTRAINT `a`
    FOREIGN KEY (`drug_id`)
    REFERENCES `pharmacy`.`drug` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `b`
    FOREIGN KEY (`client_login`)
    REFERENCES `pharmacy`.`user` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая заказы клиентов';


-- -----------------------------------------------------
-- Table `pharmacy`.`manufacturer_translate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`manufacturer_translate` (
  `language_name` VARCHAR(15) NOT NULL COMMENT 'Код языка',
  `manufacturer_id` MEDIUMINT NOT NULL COMMENT 'Идентификациионный номер предприятия',
  `name` VARCHAR(70) NOT NULL COMMENT 'Название предприятия',
  `address` VARCHAR(100) NULL COMMENT 'Адрес производителя',
  INDEX `language_code_idx` (`language_name` ASC),
  INDEX `manufacturer_id_idx` (`manufacturer_id` ASC),
  CONSTRAINT `fk_manufacturer_id_1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `pharmacy`.`manufacturer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_language_code_1`
    FOREIGN KEY (`language_name`)
    REFERENCES `pharmacy`.`language` (`language_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая локализованные данные о предприятиях';


-- -----------------------------------------------------
-- Table `pharmacy`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`country` (
  `code` VARCHAR(2) NOT NULL COMMENT 'Международный код страны(2 буквы)',
  PRIMARY KEY (`code`))
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая страны';


-- -----------------------------------------------------
-- Table `pharmacy`.`country_translate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`country_translate` (
  `country_code` VARCHAR(2) NOT NULL COMMENT 'Идентификационный номер страны',
  `lan_name` VARCHAR(15) NOT NULL COMMENT 'Код языка',
  `name` VARCHAR(40) NOT NULL COMMENT 'Название страны',
  INDEX `fk_country_code_idx` (`country_code` ASC),
  INDEX `fk_language_code_idx` (`lan_name` ASC),
  CONSTRAINT `fk_language_code_2`
    FOREIGN KEY (`lan_name`)
    REFERENCES `pharmacy`.`language` (`language_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_country_code_2`
    FOREIGN KEY (`country_code`)
    REFERENCES `pharmacy`.`country` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Таблица, хранящая локализованные названия стран';


-- -----------------------------------------------------
-- Table `pharmacy`.`language_translate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`language_translate` (
  `language_to_translate` VARCHAR(15) NOT NULL,
  `language_name` VARCHAR(15) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  INDEX `fk_language_name_a_idx` (`language_name` ASC),
  CONSTRAINT `fk_language_name`
    FOREIGN KEY (`language_to_translate`)
    REFERENCES `pharmacy`.`language` (`language_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_language_name_a`
    FOREIGN KEY (`language_name`)
    REFERENCES `pharmacy`.`language` (`language_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
